[versions]
minSdk = "21"
compileSdk = "34"
targetSdk = "34"

androidgradleplugin = "8.9.2"
kotlin = "2.1.21"
ktlint = "1.4.1"

[libraries]
kaml = "com.charleskorn.kaml:kaml:0.82.0"
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
leakcanary-android = "com.squareup.leakcanary:leakcanary-android:2.14"
material = "com.google.android.material:material:1.12.0"
okio = "com.squareup.okio:okio:3.13.0"
plugin-android-cache-fix = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin:3.0.1"
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-dokka = "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = "app.cash.licensee:licensee-gradle-plugin:1.13.0"
plugin-metalava = "me.tylerbwong.gradle.metalava:plugin:0.4.0-alpha03"
plugin-publish = "com.vanniktech:gradle-maven-publish-plugin:0.33.0"
timber = "com.jakewharton.timber:timber:5.0.1"

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
dependencygraphgenerator = { id = "com.vanniktech.dependency.graph.generator", version = "0.8.0" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
